### Arrays

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((3, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
arr_range = np.arange(10)
print(arr_range)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
lin_arr = np.linspace(0, 1, 5)
print(lin_arr)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
reshaped = arr.reshape((2, 2))
print(reshaped)

[[1 2]
 [3 4]]


In [11]:
concat = np.concatenate(([1, 2], [3, 4]))
print(concat)

[1 2 3 4]


In [12]:
print(np.sum(arr))

10


In [13]:
print(np.mean(arr))

2.5


In [14]:
unsorted = np.array([5, 2, 8, 1])
sorted_arr = np.sort(unsorted)
print(sorted_arr)

[1 2 5 8]
